# Generated by Django 5.2.17 on 2026-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('problem_statement', models.TextField()),
                ('urgency', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Deferred'), (3, 'Accepted'), (4, 'Declined')])),
                ('status_reason', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['-urgency'], name='api_item_urgency_120150_idx')],
            },
        ),
    ]
